### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by bweb79** [rodrigopolo/brripguide#1]
I keep getting an error message when trying to encode the file using the H264StereoSource.dll file. I have tried several times and remade the left.mkv file. It does not like the left.mkv as an input.

https://github.com/rodrigopolo/brripguide/blob/master/guide_en.md#encoding

![screenshot 2014-11-30 11 47 52](https://cloud.githubusercontent.com/assets/358006/5239066/3e8e6aba-7887-11e4-8b39-1681ef158b08.png)

Here is my sample.avs file

> LoadPlugin("H264StereoSource.dll")
> lv = directshowsource("left.mkv", audio=false)
> rv = H264StereoSource("decoder.cfg",127816).AssumeFPS(24000,1001)
> LeftRight3DReduced(lv, rv)

**Comment by DevilNiko** [comment]
Hi, I am getting the error in screenshot attached on running c264 encode command. Please help me.
![x264 avs h264sterosource dll error](https://cloud.githubusercontent.com/assets/19966545/16105118/0780134a-33a5-11e6-9281-f9cb79e1c122.PNG)

**Comment by rodrigopolo** [comment]
The guide has been updated to use a different approach and tools, it is simpler now:
https://github.com/rodrigopolo/brripguide/blob/master/update.md
