### ISSUE TITLE
H264StereoSource.dll loading fails

### ISSUE THREAD

**Issue by DevilNiko** [rodrigopolo/brripguide#2]
Hi, when i run x264 encode command as sample.avs input, it fails at line 1 of sample.avs saying its "unable to load H264SteroSource.dll, error=0x36b1" Could you please help me what might be causing this issue? Also attaching the screenshot for your reference.
![x264 avs h264sterosource dll error](https://cloud.githubusercontent.com/assets/19966545/16105161/6be513f8-33a5-11e6-82a2-48ae65c91f48.PNG)

**Comment by rodrigopolo** [comment]
Read the update, it is simpler now:
https://github.com/rodrigopolo/brripguide/blob/master/update.md
